env:
  global:
  - CC_TEST_REPORTER_ID=200e7e42ced51e3e2ed148ef5e5ef42aa71423b1a147728b74a36503535aa526
  - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
  - XDEBUG_ENABLED=$(if [ "$(php --version | grep -cim1 xdebug)" -ge 1 ]; then echo true; else echo false; fi)

language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-source --no-interaction --dev
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - mkdir -p build/logs
  - "phpunit --coverage-clover build/logs/clover.xml"
  - if [ "$XDEBUG_ENABLED" == "true" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

after_success:
  - travis_retry php vendor/bin/php-coveralls
